baseurl = "http://hillfolkentertainment.com"
title = "Hillfolk Entertainment Productions"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'We rise by lifting others'
  logo = "fa-tree"
  copyright = "2018 Hillfolk Entertainment Productions"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
